AUGUMENTATION: True
IMAGE_SIZE: [224, 224, 3] # As per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False # Do not include the ImageNet classifier at the top.
EPOCHS: 5
CLASSES: 8
WEIGHTS: imagenet # load weights pre-trained on imagenet
LEARNING_RATE: 0.01